### ISSUE TITLE
Fails to load if libgbm-dev is not installed on target

### ISSUE THREAD

**Issue by fredcadete** [thayama/libgbm#1]
The convention for distros is to normally install only versioned libraries (`/usr/lib/libgm.so.1.0.0` and `/usr/lib/libgbm.so.1` linking to it). `/usr/lib/libgbm.so` is provided as a symlink to the `libgbm.so.1.0.0` only if the libgm-dev package is installed. On a target machine this is normally not installed.

In backend.c, libgbm tries to load `libgm_kms.so` . To match this convention, it should load `libgbm_kms.so.1` instead.

This issue was seen and investigated in Yocto. It may vary depending on how you are using the libgbm and wayland_kms components.

**Comment by thayama** [comment]
Thank you for raising the issue. The suggested fix is accepted for now. We may need to come up with better fix though.

**Comment by fredcadete** [comment]
Thanks for accepting this. Certainly, a better solution would be nice. This one will only work if the buildsystem considers that libgm is version 1.
But already this patch can avoid workarounds such as GENIVI always installing libgm-dev (http://git.projects.genivi.org/?p=meta-genivi-demo.git;a=blob;f=recipes-demo-platform/images/genivi-demo-platform.bb;h=9a2740e8210fb060a6519c5efaac5f3c351eaf36;hb=HEAD#l36)
